{{ if .Values.secrets.imageRegistry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.imageRegistry.prefixName }}-image-registry-secret
data:
  .dockerconfigjson: {{ include "extranet-apigateway.imageRegistry" . | b64enc }}
type: kubernetes.io/dockerconfigjson
{{ end }}
