replicaCount: 1

global: 
  imageRegistry: ghcr.io/extranetsrl

nameOverride: ""
fullnameOverride: ""

extranetrecruitmentsapi:
  image:
    repository: extranet.recruitments-api
    pullPolicy: Always

extranetrecruitmentsjob:
  image:
    repository: extranet.recruitments-job
    pullPolicy: Always

k8swaitfor:
  image:
    repository: ghcr.io/groundnuty/k8s-wait-for
    pullPolicy: Always
    tag: v2.0

service:
  type: ClusterIP
  port: 80

postgresql:
  hostname: postgresql-ha-postgresql
  namespace: postgresql-ha
  port: 5432
  auth:
    username: myuser
    password: mypassword
    database: mydb

secrets:
  imageRegistry:
    enabled: false
    prefixName: ""
    address: ""
    username: ""
    password: ""