replicaCount: 1

global: 
  imageRegistry: ghcr.io/extranetsrl

nameOverride: ""
fullnameOverride: ""

extranetidentityapi:
  image:
    repository: extranet.identity-api
    pullPolicy: Always

extranetidentityjob:
  image:
    repository: extranet.identity-job
    pullPolicy: Always

k8swaitfor:
  image:
    repository: ghcr.io/groundnuty/k8s-wait-for
    pullPolicy: Always
    tag: v2.0

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP
  name: http

env:
  - name: KeycloakClient__KeycloakBaseUrl 
    value: http://keycloak.keycloak.svc.cluster.local/keycloak/
  - name: KeycloakClient__Username 
    value: myuser
  - name: KeycloakClient__Password 
    value: mypassword

secrets:
  imageRegistry:
    enabled: false
    prefixName: ""
    address: ""
    username: ""
    password: ""